
version: 2

models:
    - name: inscritos
      description: "Nome e idade dos inscritos"
      columns:
          - name: Name
            description: "Nome dos inscritos"
            tests:
                - unique
                

    - name: stage_inscritos
      description: "Dados de inscritos transformados"
      columns:
          - name: majority
            description: "True se a idade for maior que 25"
            tests:
                - not_null

    - name: analise_inscritos
      description: "Agrupamento de maioridades"
      columns:
        - name: majority
          description: "Aceitar somente valores True e False"
          tests:
            - accepted_values:
                values: [true, false]
                quote: false