
version: 2

sources:
  - name: dbt_projects
    description: Dataset de RH
    database: portfolio-101-417118
    schema: dbt_projects
    tables:
      - name: tabela_rh
        description: Tabela com dados de RH
